FROM openjdk:17-slim
WORKDIR /app

COPY target/api-gateway-0.0.1-SNAPSHOT.jar app.jar

EXPOSE 8080
ENTRYPOINT ["java", "-cp", "api-gateway-0.0.1-SNAPSHOT.jar:/app/libs/*", "org.upnext.apigateway.ApiGatewayApplication"]
